### ISSUE TITLE
Nested routing

### ISSUE THREAD

**Issue by mcallisto** [mcallisto/slinky-react-router.g8#2]
It uses [match](https://reacttraining.com/react-router/web/api/match).
Not found yet a proper way to code it.

**Comment by oyvindberg** [comment]
Is [this](https://reacttraining.com/react-router/web/example/recursive-paths) what you're talking about? 
You have `match` available in the parameter you discard in `render` [here](https://github.com/mcallisto/slinky-react-router.g8/blob/master/src/main/g8/src/main/scala/%24package%24/App.scala#L75)

**Comment by mcallisto** [comment]
@oyvindberg thank you for pointing me in the right direction
